xcodeproj 'Tests'
workspace '../Typhoon'

def import_test_pods
  pod 'OCHamcrest', '~> 1.9'
  pod 'OCMockito', '~> 0.2'
end

def import_typhoon_pod
  pod 'Typhoon', :path => '../'
end

target 'iOS Tests (Static Library)' do
  platform :ios, '5.0'
  import_test_pods
end

target 'iOS Tests (Cocoapods)' do
  platform :ios, '5.0'
  import_test_pods
  import_typhoon_pod
end

target 'OS X Tests (Cocoapods)' do
  platform :osx, '10.7'
  import_test_pods
  import_typhoon_pod
end

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_GENERATE_TEST_COVERAGE_FILES'] = 'YES'
      config.build_settings['GCC_INSTRUMENT_PROGRAM_FLOW_ARCS'] = 'YES'
    end
  end
end

